<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Grade Alert – Clash of Subject</title>
  <style>
    body { margin: 0; padding: 0; background: #0a0c18; font-family: 'Courier New', Courier, monospace; }
    .container { max-width: 600px; margin: 30px auto; background: #0e1530; border: 2px solid #1e2a50; box-shadow: 0 0 0 1px #f0c030, 6px 6px 0 #7a6000; }
    .header { background: #090d1e; padding: 28px 32px; border-bottom: 3px solid #f0c030; text-align: center; }
    .header h1 { font-size: 18px; color: #f0c030; text-shadow: 2px 2px 0 #7a6000; letter-spacing: 0.1em; margin: 0 0 8px; }
    .header p  { font-size: 13px; color: rgba(180,200,255,0.6); margin: 0; letter-spacing: 0.15em; }
    .body { padding: 32px; }
    .greeting { font-size: 15px; color: rgba(220,235,255,0.9); margin-bottom: 20px; line-height: 1.7; }
    .grade-card { background: #090d1e; border: 2px solid #c0392b; box-shadow: 4px 4px 0 #7b241c; padding: 20px 24px; margin: 24px 0; border-radius: 0; }
    .grade-card .label { font-size: 10px; color: rgba(180,200,255,0.5); letter-spacing: 0.12em; text-transform: uppercase; margin-bottom: 6px; }
    .grade-card .value { font-size: 20px; color: #f0c030; letter-spacing: 0.08em; margin-bottom: 14px; }
    .grade-card .pct   { font-size: 42px; color: #c0392b; font-weight: bold; letter-spacing: 0.05em; text-align: center; padding: 10px 0; border: 2px solid rgba(192,57,43,0.4); margin-top: 8px; }
    .alert-box { background: rgba(192,57,43,0.12); border-left: 4px solid #c0392b; padding: 14px 18px; margin: 20px 0; font-size: 14px; color: #e57373; line-height: 1.7; }
    .tips { margin: 20px 0; }
    .tips h3  { font-size: 11px; color: #f0c030; letter-spacing: 0.1em; text-transform: uppercase; margin-bottom: 12px; border-bottom: 1px solid #1e2a50; padding-bottom: 8px; }
    .tips ul  { padding-left: 20px; margin: 0; }
    .tips li  { font-size: 13px; color: rgba(200,215,255,0.8); margin-bottom: 8px; line-height: 1.6; }
    .message  { font-size: 14px; color: rgba(200,215,255,0.7); line-height: 1.8; margin-top: 20px; }
    .footer   { background: #090d1e; border-top: 2px solid #1e2a50; padding: 18px 32px; text-align: center; font-size: 11px; color: rgba(140,170,230,0.4); letter-spacing: 0.1em; }
    .pixel-bar { height: 4px; background: linear-gradient(90deg, #c0392b, #f0c030, #c0392b); }
  </style>
</head>
<body>
  <div class="container">
    <div class="pixel-bar"></div>
    <div class="header">
      <h1>⚔ CLASH OF SUBJECT</h1>
      <p>GRADE PERFORMANCE ALERT</p>
    </div>

    <div class="body">
      <p class="greeting">
        Dear <strong style="color:#f0c030;">{{ $studentName }}</strong>,<br><br>
        This is an automated notification from the <strong>Clash of Subject</strong> system. 
        A recent grade record has been flagged because it falls below the passing threshold of <strong style="color:#f0c030;">75%</strong>.
      </p>

      <div class="grade-card">
        <div class="label">Subject</div>
        <div class="value">{{ strtoupper($subjectName) }}</div>
        <div class="label">Assessment Type</div>
        <div class="value">{{ strtoupper($type) }}</div>
        <div class="label">Grade Received</div>
        <div class="pct">{{ $grade }}%</div>
      </div>

      <div class="alert-box">
        ⚠️ This grade is <strong>below the passing mark of 75%</strong>. Immediate attention and additional effort are recommended for this subject.
      </div>

      <div class="tips">
        <h3>📚 Recommended Actions</h3>
        <ul>
          <li>Review the learning materials related to <strong style="color:#f0c030;">{{ strtoupper($subjectName) }}</strong> thoroughly.</li>
          <li>Practice consistently using the <strong>Clash of Subject</strong> gameplay to have an Interactive Learning Experience.</li>
          <li>Reach out to your teacher for additional guidance and assistance.</li>
          <li>Form a study group with classmates to strengthen understanding.</li>
          <li>Ask your teacher for extra exercises or review materials.</li>
        </ul>
      </div>

      <p class="message">
        This student <strong>requires more assistance in {{ strtoupper($subjectName) }}</strong>. 
        We encourage you to take this as a learning opportunity and work closely with your teacher to improve your performance. 
        You can do it! 💪
      </p>

      <p class="message" style="color: rgba(140,170,230,0.5); font-size: 12px; margin-top: 28px;">
        This email was automatically generated by the Clash of Subject grading system. 
        Please do not reply to this email.
      </p>
    </div>

    <div class="footer">
      ⚔ CLASH OF SUBJECT SYSTEM &nbsp;|&nbsp; AUTOMATED GRADE MONITOR
    </div>
    <div class="pixel-bar"></div>
  </div>
</body>
</html>
